# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import todo_pb2 as protos_dot_todo__pb2


class TodoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createTodo = channel.unary_unary(
                '/todoPackage.Todo/createTodo',
                request_serializer=protos_dot_todo__pb2.TodoItem.SerializeToString,
                response_deserializer=protos_dot_todo__pb2.TodoItem.FromString,
                )
        self.getTodo = channel.unary_unary(
                '/todoPackage.Todo/getTodo',
                request_serializer=protos_dot_todo__pb2.TodoItem.SerializeToString,
                response_deserializer=protos_dot_todo__pb2.TodoItem.FromString,
                )
        self.updateTodo = channel.unary_unary(
                '/todoPackage.Todo/updateTodo',
                request_serializer=protos_dot_todo__pb2.TodoItem.SerializeToString,
                response_deserializer=protos_dot_todo__pb2.TodoItem.FromString,
                )
        self.deleteTodo = channel.unary_unary(
                '/todoPackage.Todo/deleteTodo',
                request_serializer=protos_dot_todo__pb2.TodoItem.SerializeToString,
                response_deserializer=protos_dot_todo__pb2.TodoItem.FromString,
                )
        self.listTodo = channel.unary_stream(
                '/todoPackage.Todo/listTodo',
                request_serializer=protos_dot_todo__pb2.TodoItem.SerializeToString,
                response_deserializer=protos_dot_todo__pb2.TodoItem.FromString,
                )


class TodoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def createTodo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getTodo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateTodo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteTodo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listTodo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TodoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.createTodo,
                    request_deserializer=protos_dot_todo__pb2.TodoItem.FromString,
                    response_serializer=protos_dot_todo__pb2.TodoItem.SerializeToString,
            ),
            'getTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.getTodo,
                    request_deserializer=protos_dot_todo__pb2.TodoItem.FromString,
                    response_serializer=protos_dot_todo__pb2.TodoItem.SerializeToString,
            ),
            'updateTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.updateTodo,
                    request_deserializer=protos_dot_todo__pb2.TodoItem.FromString,
                    response_serializer=protos_dot_todo__pb2.TodoItem.SerializeToString,
            ),
            'deleteTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteTodo,
                    request_deserializer=protos_dot_todo__pb2.TodoItem.FromString,
                    response_serializer=protos_dot_todo__pb2.TodoItem.SerializeToString,
            ),
            'listTodo': grpc.unary_stream_rpc_method_handler(
                    servicer.listTodo,
                    request_deserializer=protos_dot_todo__pb2.TodoItem.FromString,
                    response_serializer=protos_dot_todo__pb2.TodoItem.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'todoPackage.Todo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Todo(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def createTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/todoPackage.Todo/createTodo',
            protos_dot_todo__pb2.TodoItem.SerializeToString,
            protos_dot_todo__pb2.TodoItem.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/todoPackage.Todo/getTodo',
            protos_dot_todo__pb2.TodoItem.SerializeToString,
            protos_dot_todo__pb2.TodoItem.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def updateTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/todoPackage.Todo/updateTodo',
            protos_dot_todo__pb2.TodoItem.SerializeToString,
            protos_dot_todo__pb2.TodoItem.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/todoPackage.Todo/deleteTodo',
            protos_dot_todo__pb2.TodoItem.SerializeToString,
            protos_dot_todo__pb2.TodoItem.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def listTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/todoPackage.Todo/listTodo',
            protos_dot_todo__pb2.TodoItem.SerializeToString,
            protos_dot_todo__pb2.TodoItem.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
